In [39]:
import pandas as pd

In [40]:
vehiculos = pd.read_csv("VEHICULOS_INVOLUCRADOS_EN_UN_ACCIDENTE_DE_TRANSITO.csv")
victimas = pd.read_csv("Homicidios_accidente_de_tránsito.csv")

/var/folders/x1/c2vl7bg55zbc38s9nn3zm61c0000gn/T/ipykernel_44493/369847558.py:1: DtypeWarning: Columns (0: EDAD_VEHICULO) have mixed types. Specify dtype option on import or set low_memory=False.
  vehiculos = pd.read_csv("VEHICULOS_INVOLUCRADOS_EN_UN_ACCIDENTE_DE_TRANSITO.csv")

In [41]:
vehiculos.info()

<class 'pandas.DataFrame'>
RangeIndex: 406540 entries, 0 to 406539
Data columns (total 9 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   MARCA_VEHICULO          406496 non-null  str
 1   MODELO_VEHICULO         406540 non-null  int64
 2   TIPO_VEHICULO           406540 non-null  str
 3   EDAD_VEHICULO           406520 non-null  object
 4   FECHA_ACCIDENTE         406540 non-null  str
 5   GRAVEDAD_ACCIDENTE      406540 non-null  str
 6   DEPARTAMENTO_ACCIDENTE  406540 non-null  str
 7   MUNICIPIO_ACCIDENTE     406540 non-null  str
 8   AUTORIDAD_DE_TRANSITO   406540 non-null  str
dtypes: int64(1), object(1), str(7)
memory usage: 27.9+ MB

In [48]:
victimas.info()

<class 'pandas.DataFrame'>
RangeIndex: 95239 entries, 0 to 95238
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   DEPARTAMENTO          95239 non-null  str
 1   MUNICIPIO             95239 non-null  str
 2   CODIGO DANE           95239 non-null  int64
 3   ARMAS MEDIOS          95239 non-null  str
 4   FECHA HECHO           95239 non-null  str
 5   GENERO                95041 non-null  str
 6   GRUPO ETARÍO          95088 non-null  str
 7   DESCRIPCIÓN CONDUCTA  95239 non-null  str
 8   CANTIDAD              95239 non-null  int64
dtypes: int64(2), str(7)
memory usage: 6.5 MB

In [42]:
# Revisamos el tipo de datos en la columna de edad del vehículo ya que están en diferentes tipos de variables.
vehiculos["EDAD_VEHICULO"].unique()

array([9.0, 20.0, 2.0, 1.0, 0.0, 13.0, 4.0, 11.0, 8.0, 10.0, 5.0, 15.0,
       23.0, 18.0, 44.0, 3.0, 22.0, 17.0, 19.0, 6.0, 14.0, 16.0, nan,
       27.0, 7.0, 30.0, 12.0, 28.0, 21.0, 31.0, 33.0, 51.0, 25.0, 70.0,
       24.0, 32.0, 26.0, 29.0, 68.0, 46.0, 41.0, 47.0, 35.0, 37.0, 34.0,
       58.0, 36.0, 48.0, 66.0, 57.0, 50.0, 53.0, 38.0, 45.0, 39.0, 59.0,
       54.0, 60.0, 71.0, 64.0, 43.0, 42.0, 65.0, 56.0, 73.0, 40.0, 76.0,
       49.0, 126.0, 72.0, 52.0, 55.0, 62.0, 75.0, 61.0, 77.0, 63.0, 74.0,
       69.0, 67.0, 106.0, 78.0, 84.0, 86.0, 80.0, 79.0, '5', '20', '4',
       '16', '6', '15', '14', '7', '18', '21', '12', '13', '10', '9', '3',
       '19', '39', '11', '8', '22', '49', '17', '27', '23', '41', '37',
       '30', '29', '28', '31', '34', '25', '33', '24', '38', '42', '26',
       '35', '47', '52', '36', '32', '40', '44', '45', '51', '46', '63',
       '57', '48', '66', '54', '56', '71', '126', '69', '70', '43', '50',
       '73', '55', '59', '58', '61', '67', '1', '0', '2', '53', '60',
       '65', '72', '74', '77', '1,826', '80', '68', '62', '64', '76'],
      dtype=object)

In [43]:
# Separamos el año y el año del accidente para poder calcular de forma acertada la edad del vehiculo al momento del accidente

vehiculos["AÑO_ACCIDENTE"] = vehiculos["FECHA_ACCIDENTE"].str.split("/").str[1].astype(int)
vehiculos["MES_ACCIDENTE"] = vehiculos["FECHA_ACCIDENTE"].str.split("/").str[0].astype(int)

In [44]:
# Calculamos la edad del vehículo al momento del accidente, restando el año del accidente al modelo del vehículo

vehiculos["EDAD_VEHICULO"] = vehiculos["AÑO_ACCIDENTE"] - vehiculos["MODELO_VEHICULO"]

# Cambiamos los valores menores a CERO por CERO para evitar errores
vehiculos.loc[vehiculos["EDAD_VEHICULO"] < 0, "EDAD_VEHICULO"] = 0

In [46]:
vehiculos.head(20)

,MARCA_VEHICULO,MODELO_VEHICULO,TIPO_VEHICULO,EDAD_VEHICULO,FECHA_ACCIDENTE,GRAVEDAD_ACCIDENTE,DEPARTAMENTO_ACCIDENTE,MUNICIPIO_ACCIDENTE,AUTORIDAD_DE_TRANSITO,AÑO_ACCIDENTE,MES_ACCIDENTE
0,HONDA,2017,MOTOCICLETA,8,12/2025,CON HERIDOS,SANTANDER,BUCARAMANGA,DIR TTOyTTE BUCARAMANGA,2025,12
1,CHEVROLET,2007,CAMION,18,12/2025,CON HERIDOS,SANTANDER,BUCARAMANGA,DIR TTOyTTE BUCARAMANGA,2025,12
2,JEEP,2017,CAMPERO,8,12/2025,CON HERIDOS,SANTANDER,BUCARAMANGA,DIR TTOyTTE BUCARAMANGA,2025,12
3,CHEVROLET,2023,CAMIONETA,2,12/2025,CON HERIDOS,SANTANDER,BUCARAMANGA,DIR TTOyTTE BUCARAMANGA,2025,12
4,HONDA,2026,MOTOCICLETA,0,12/2025,CON HERIDOS,SANTANDER,BUCARAMANGA,DIR TTOyTTE BUCARAMANGA,2025,12
5,BERA,2025,MOTOCICLETA,0,12/2025,CON HERIDOS,SANTANDER,BUCARAMANGA,DIR TTOyTTE BUCARAMANGA,2025,12
6,HONDA,2026,MOTOCICLETA,0,12/2025,CON HERIDOS,SANTANDER,BUCARAMANGA,DIR TTOyTTE BUCARAMANGA,2025,12
7,NISSAN,2013,CAMIONETA,12,12/2025,CON HERIDOS,SANTANDER,BUCARAMANGA,DIR TTOyTTE BUCARAMANGA,2025,12
8,HONDA,2022,MOTOCICLETA,3,12/2025,CON HERIDOS,SANTANDER,BUCARAMANGA,DIR TTOyTTE BUCARAMANGA,2025,12
9,MAZDA,2025,CAMIONETA,0,12/2025,CON HERIDOS,SANTANDER,BUCARAMANGA,DIR TTOyTTE BUCARAMANGA,2025,12
10,CHEVROLET,2016,AUTOMOVIL,9,12/2025,CON HERIDOS,SANTANDER,BUCARAMANGA,DIR TTOyTTE BUCARAMANGA,2025,12
11,HONDA,2026,MOTOCICLETA,0,12/2025,CON HERIDOS,SANTANDER,BUCARAMANGA,DIR TTOyTTE BUCARAMANGA,2025,12
12,CHEVROLET,2018,AUTOMOVIL,7,12/2025,CON HERIDOS,SANTANDER,BUCARAMANGA,DIR TTOyTTE BUCARAMANGA,2025,12
13,CHEVROLET,2016,AUTOMOVIL,9,12/2025,CON HERIDOS,SANTANDER,BUCARAMANGA,DIR TTOyTTE BUCARAMANGA,2025,12
14,HONDA,2022,MOTOCICLETA,3,12/2025,CON HERIDOS,SANTANDER,BUCARAMANGA,DIR TTOyTTE BUCARAMANGA,2025,12
15,CHERY,2011,AUTOMOVIL,14,12/2025,CON HERIDOS,SANTANDER,BUCARAMANGA,DIR TTOyTTE BUCARAMANGA,2025,12
16,CHEVROLET,2003,BUS,22,12/2025,CON HERIDOS,SANTANDER,BUCARAMANGA,DIR TTOyTTE BUCARAMANGA,2025,12
17,CHEVROLET,2008,AUTOMOVIL,17,12/2025,CON HERIDOS,SANTANDER,BUCARAMANGA,DIR TTOyTTE BUCARAMANGA,2025,12
18,MAZDA,2003,AUTOMOVIL,22,12/2025,CON HERIDOS,SANTANDER,BUCARAMANGA,DIR TTOyTTE BUCARAMANGA,2025,12
19,BERA,2025,MOTOCICLETA,0,12/2025,CON HERIDOS,SANTANDER,BUCARAMANGA,DIR TTOyTTE BUCARAMANGA,2025,12

In [47]:
victimas.head(20)

,DEPARTAMENTO,MUNICIPIO,CODIGO DANE,ARMAS MEDIOS,FECHA HECHO,GENERO,GRUPO ETARÍO,DESCRIPCIÓN CONDUCTA,CANTIDAD
0,CAUCA,Cajibío,19130000,NO REPORTADO,13/02/2014,MASCULINO,ADULTOS,ARTÍCULO 109. HOMICIDIO CULPOSO ( EN ACCIDENTE...,1
1,CAUCA,Santander de Quilichao,19698000,NO REPORTADO,15/02/2014,MASCULINO,MENORES,ARTÍCULO 109. HOMICIDIO CULPOSO ( EN ACCIDENTE...,1
2,GUAJIRA,Riohacha (CT),44001000,NO REPORTADO,15/02/2014,MASCULINO,ADULTOS,ARTÍCULO 109. HOMICIDIO CULPOSO ( EN ACCIDENTE...,1
3,BOYACÁ,Puerto Boyacá,15572000,NO REPORTADO,19/01/2014,FEMENINO,ADULTOS,ARTÍCULO 109. HOMICIDIO CULPOSO ( EN ACCIDENTE...,1
4,CAUCA,Cajibío,19130000,NO REPORTADO,23/02/2014,MASCULINO,ADULTOS,ARTÍCULO 109. HOMICIDIO CULPOSO ( EN ACCIDENTE...,1
5,CAUCA,Villa Rica,19845000,NO REPORTADO,01/03/2014,MASCULINO,MENORES,ARTÍCULO 109. HOMICIDIO CULPOSO ( EN ACCIDENTE...,1
6,MAGDALENA,Santa Marta (CT),47001000,NO REPORTADO,27/02/2014,MASCULINO,ADULTOS,ARTÍCULO 109. HOMICIDIO CULPOSO ( EN ACCIDENTE...,1
7,ATLÁNTICO,Baranoa,8078000,NO REPORTADO,08/02/2014,MASCULINO,ADULTOS,ARTÍCULO 109. HOMICIDIO CULPOSO ( EN ACCIDENTE...,1
8,ATLÁNTICO,Baranoa,8078000,NO REPORTADO,08/02/2014,MASCULINO,ADULTOS,ARTÍCULO 109. HOMICIDIO CULPOSO ( EN ACCIDENTE...,1
9,CÓRDOBA,Tierralta,23807000,NO REPORTADO,07/03/2014,FEMENINO,ADOLESCENTES,ARTÍCULO 109. HOMICIDIO CULPOSO ( EN ACCIDENTE...,1
10,CASANARE,Paz de Ariporo,85250000,NO REPORTADO,10/01/2013,MASCULINO,ADULTOS,ARTÍCULO 109. HOMICIDIO CULPOSO ( EN ACCIDENTE...,1
11,CASANARE,San Luis de Palenque,85325000,NO REPORTADO,21/04/2013,FEMENINO,ADULTOS,ARTÍCULO 109. HOMICIDIO CULPOSO ( EN ACCIDENTE...,1
12,CASANARE,Trinidad,85430000,NO REPORTADO,18/04/2013,MASCULINO,ADULTOS,ARTÍCULO 109. HOMICIDIO CULPOSO ( EN ACCIDENTE...,1
13,CASANARE,Monterrey,85162000,NO REPORTADO,26/07/2013,MASCULINO,ADULTOS,ARTÍCULO 109. HOMICIDIO CULPOSO ( EN ACCIDENTE...,1
14,CASANARE,Paz de Ariporo,85250000,NO REPORTADO,12/05/2013,MASCULINO,ADULTOS,ARTÍCULO 109. HOMICIDIO CULPOSO ( EN ACCIDENTE...,1
15,CASANARE,Aguazul,85010000,NO REPORTADO,10/08/2013,FEMENINO,ADOLESCENTES,ARTÍCULO 109. HOMICIDIO CULPOSO ( EN ACCIDENTE...,1
16,CASANARE,Hato Corozal,85125000,NO REPORTADO,31/05/2013,MASCULINO,ADULTOS,ARTÍCULO 109. HOMICIDIO CULPOSO ( EN ACCIDENTE...,1
17,CASANARE,Monterrey,85162000,NO REPORTADO,02/02/2013,MASCULINO,ADULTOS,ARTÍCULO 109. HOMICIDIO CULPOSO ( EN ACCIDENTE...,1
18,CASANARE,Tauramena,85410000,NO REPORTADO,20/05/2013,MASCULINO,ADULTOS,ARTÍCULO 109. HOMICIDIO CULPOSO ( EN ACCIDENTE...,1
19,CASANARE,Villanueva,85440000,NO REPORTADO,06/02/2013,MASCULINO,ADULTOS,ARTÍCULO 109. HOMICIDIO CULPOSO ( EN ACCIDENTE...,1

In [61]:
victimas["GENERO"].value_counts()

GENERO
MASCULINO     76141
FEMENINO      18885
NO REPORTA       15
Name: count, dtype: int64

In [49]:
vehiculos.columns

Index(['MARCA_VEHICULO', 'MODELO_VEHICULO', 'TIPO_VEHICULO', 'EDAD_VEHICULO',
       'FECHA_ACCIDENTE', 'GRAVEDAD_ACCIDENTE', 'DEPARTAMENTO_ACCIDENTE',
       'MUNICIPIO_ACCIDENTE', 'AUTORIDAD_DE_TRANSITO', 'AÑO_ACCIDENTE',
       'MES_ACCIDENTE'],
      dtype='str')

In [52]:
victimas.columns

Index(['DEPARTAMENTO', 'MUNICIPIO', 'CODIGO DANE', 'ARMAS MEDIOS',
       'FECHA HECHO', 'GENERO', 'GRUPO ETARÍO', 'CANTIDAD'],
      dtype='str')

In [ ]:
#Eliminamos columnas innecesarias
victimas = victimas.drop(columns=["DESCRIPCIÓN CONDUCTA"])

In [57]:
#Revisamos nulos en los datasets.
vehiculos.isnull().sum()

MARCA_VEHICULO            44
MODELO_VEHICULO            0
TIPO_VEHICULO              0
EDAD_VEHICULO              0
FECHA_ACCIDENTE            0
GRAVEDAD_ACCIDENTE         0
DEPARTAMENTO_ACCIDENTE     0
MUNICIPIO_ACCIDENTE        0
AUTORIDAD_DE_TRANSITO      0
AÑO_ACCIDENTE              0
MES_ACCIDENTE              0
dtype: int64

In [56]:
#Revisamos nulos en los datasets.
victimas.isnull().sum()

DEPARTAMENTO      0
MUNICIPIO         0
CODIGO DANE       0
ARMAS MEDIOS      0
FECHA HECHO       0
GENERO          198
GRUPO ETARÍO    151
CANTIDAD          0
dtype: int64

In [58]:
#Crear un resumen rápido de cada dataset
vehiculos.describe()

       MODELO_VEHICULO  EDAD_VEHICULO  AÑO_ACCIDENTE  MES_ACCIDENTE
count    406540.000000  406540.000000  406540.000000  406540.000000
mean       2015.587573       7.763197    2023.315664       6.411217
std           7.817606       7.769781       1.047380       3.323220
min        1937.000000       0.000000    2022.000000       1.000000
25%        2012.000000       2.000000    2022.000000       4.000000
50%        2017.000000       6.000000    2023.000000       7.000000
75%        2021.000000      11.000000    2024.000000       9.000000
max        2027.000000      87.000000    2026.000000      12.000000

In [59]:
#Crear un resumen rápido de cada dataset
victimas.describe()

        CODIGO DANE  CANTIDAD
count  9.523900e+04   95239.0
mean   3.749299e+07       1.0
std    2.725838e+07       0.0
min    5.001000e+06       1.0
25%    1.100100e+07       1.0
50%    2.547300e+07       1.0
75%    6.800100e+07       1.0
max    9.977300e+07       1.0

## Análisis exploratorio

In [62]:
# ¿Cuántos accidentes terminaron con muertos y cuántos con heridos?

vehiculos["GRAVEDAD_ACCIDENTE"].value_counts()

GRAVEDAD_ACCIDENTE
CON HERIDOS    385881
CON MUERTOS     20659
Name: count, dtype: int64

In [63]:
# ¿Qué porcentaje representa cada uno?

vehiculos["GRAVEDAD_ACCIDENTE"].value_counts(normalize=True)*100

GRAVEDAD_ACCIDENTE
CON HERIDOS    94.918335
CON MUERTOS     5.081665
Name: proportion, dtype: float64

In [64]:
# ¿Qué tipos de vehículo aparecen más frecuentemente?

vehiculos["TIPO_VEHICULO"].value_counts().head(10)

TIPO_VEHICULO
MOTOCICLETA     229212
AUTOMOVIL        92166
CAMIONETA        34270
BUS              16127
CAMION           10840
CAMPERO           8590
TRACTOCAMION      5059
MICROBUS          4325
BUSETA            2845
VOLQUETA          1971
Name: count, dtype: int64

In [65]:
# ¿Cuáles son los departamentos con más accidentes?

vehiculos["DEPARTAMENTO_ACCIDENTE"].value_counts().head(10)

DEPARTAMENTO_ACCIDENTE
ANTIOQUIA          162012
BOGOTA D.C.         60350
VALLE DEL CAUCA     49560
SANTANDER           16857
ATLANTICO           13834
CUNDINAMARCA        11925
TOLIMA              10864
RISARALDA           10780
BOLIVAR              8761
CALDAS               8742
Name: count, dtype: int64

In [66]:
# ¿Cuál es la edad promedio de los vehículos según la gravedad?

vehiculos.groupby("GRAVEDAD_ACCIDENTE")["EDAD_VEHICULO"].mean()

GRAVEDAD_ACCIDENTE
CON HERIDOS    7.682311
CON MUERTOS    9.274021
Name: EDAD_VEHICULO, dtype: float64

In [67]:
vehiculos["MARCA_VEHICULO"].value_counts().head(10)

MARCA_VEHICULO
BAJAJ        53036
YAMAHA       51091
CHEVROLET    46343
AKT          31805
HONDA        25336
SUZUKI       22767
RENAULT      19677
HYUNDAI      19631
KIA          18801
TVS          11669
Name: count, dtype: int64

In [68]:
kpis = {
    "total_vehiculos": len(vehiculos),
    "accidentes_heridos": (vehiculos["GRAVEDAD_ACCIDENTE"] == "CON HERIDOS").sum(),
    "accidentes_muertos": (vehiculos["GRAVEDAD_ACCIDENTE"] == "CON MUERTOS").sum(),
    "edad_promedio": round(vehiculos["EDAD_VEHICULO"].mean(), 1)
}

kpis

{'total_vehiculos': 406540,
 'accidentes_heridos': np.int64(385881),
 'accidentes_muertos': np.int64(20659),
 'edad_promedio': np.float64(7.8)}

In [69]:
vehiculos["MUNICIPIO_ACCIDENTE"].value_counts().head(10)

MUNICIPIO_ACCIDENTE
MEDELLIN        111105
BOGOTA           60350
CALI             30300
BARRANQUILLA     12595
BUCARAMANGA       9277
BELLO             8857
IBAGUE            8069
PEREIRA           7704
CARTAGENA         7550
ITAGUI            6440
Name: count, dtype: int64

In [70]:
victimas.groupby("GRUPO ETARÍO")["CANTIDAD"].sum()

GRUPO ETARÍO
ADOLESCENTES     3596
ADULTOS         89335
MENORES          2157
Name: CANTIDAD, dtype: int64